############################
## CHANGE THESE
############################

baseURL: "https://glennji.github.io/qubt-scifidad"
title: qubt-scifidad

############################
## MISC
############################

enableEmoji: true
disableKinds: ["taxonomy", "term"]
languageCode: "en-us"
enableRobotsTXT: true
