## Author
author:
  name: scifidad
  image: author.jpg
  greeting: Father, futurist, sci-fan, technologist, gamer, retro-geek, dreamer.
  icon: ":tumbler_glass:"

## Comments
services:
  disqus:
    shortname: scifidad_comments



## Links
links:
  - email: scifidad@proton.me
  - youtube: https://www.youtube.com/@scifidad
  - bluesky: https://bsky.app/profile/scifidad.com
  - medium: https://medium.com/@scifidad_writing
  - link: https://scifidad.com/uses
  # - bitbucket: 
  # - bandcamp: 
  # - etsy: 
  # - spotify: 
  # - pinterest: 
  # - strava: 
  # - untappd: 
  # - skype: 
  # - keybase:
  # - flickr:
  # - tumblr:
  # - kickstarter:
  # - snapchat:
  # - discord:
  # - orcid:
  # - slack:
  # - stack-overflow:
  # - twitch:
  # - patreon:
  # - soundcloud:
  # - dribbble:
  # - stack-exchange:
  # - tiktok:
  #- github:
  # - link:
  # - website:
  # - x-twitter:
  # - mastodon:
  # - linkedin:
  # - instagram:
  # - reddit:
  # - telegram:
  # - whatsapp:
  # - signal:
  # - codepen:
  # - dev:
  # - foursquare: 
  # - apple: 
  # - amazon:
  # - google:
  # - paypal:
  # - windows:

###############################
## OpenGraph & Twitter Cards
###############################

title: scifidad
description: "scifidad exploring space-time"
images:
  - thumbnail.jpg
